### ISSUE TITLE
Getting a 429 error when using tthe 

### ISSUE THREAD

**Issue by sp2410** [microlinkhq/youtube-dl-exec#10]
Hello,
I am using the library inside an express.js application.
My dependencies are mainly:
`  "dependencies": {
    "express": "^4.17.1",
    "youtube-dl-exec": "^1.2.0"
  },
  "devDependencies": {
    "jest": "^26.6.3",
    "nodemon": "^2.0.7",
    "prettier": "2.2.1"
  }`

Works well with local testing but when deploying to Heroku I am getting the following error:

`ERROR: Unable to download webpage: HTTP Error 429: - (caused by <HTTPError 429: '-'>);`

Is this a common issue? Do we get 429 because of Instagram blocking the request?

Attched is my full heroku log:
`Error: Command failed with exit code 1: /app/node_modules/youtube-dl-exec/bin/youtube-dl https://www.instagram.com/p/CCRq_InFZ44 --dump-json --no-warnings --no-call-home --no-check-certificate --prefer-free-formats --youtube-skip-dash-manifest
2021-04-06T23:52:47.208255+00:00 app[web.1]: ERROR: Unable to download webpage: HTTP Error 429: - (caused by <HTTPError 429: '-'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
2021-04-06T23:52:47.208256+00:00 app[web.1]: at makeError (/app/node_modules/youtube-dl-exec/node_modules/execa/lib/error.js:59:11)
2021-04-06T23:52:47.208256+00:00 app[web.1]: at handlePromise (/app/node_modules/youtube-dl-exec/node_modules/execa/index.js:114:26)
2021-04-06T23:52:47.208257+00:00 app[web.1]: at processTicksAndRejections (node:internal/process/task_queues:94:5) {
2021-04-06T23:52:47.208257+00:00 app[web.1]: shortMessage: 'Command failed with exit code 1: /app/node_modules/youtube-dl-exec/bin/youtube-dl https://www.instagram.com/p/CCRq_InFZ44 --dump-json --no-warnings --no-call-home --no-check-certificate --prefer-free-formats --youtube-skip-dash-manifest',
2021-04-06T23:52:47.208260+00:00 app[web.1]: command: '/app/node_modules/youtube-dl-exec/bin/youtube-dl https://www.instagram.com/p/CCRq_InFZ44 --dump-json --no-warnings --no-call-home --no-check-certificate --prefer-free-formats --youtube-skip-dash-manifest',
2021-04-06T23:52:47.208260+00:00 app[web.1]: exitCode: 1,
2021-04-06T23:52:47.208260+00:00 app[web.1]: signal: undefined,
2021-04-06T23:52:47.208261+00:00 app[web.1]: signalDescription: undefined,
2021-04-06T23:52:47.208261+00:00 app[web.1]: stdout: '',
2021-04-06T23:52:47.208262+00:00 app[web.1]: stderr: "ERROR: Unable to download webpage: HTTP Error 429: - (caused by <HTTPError 429: '-'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",
2021-04-06T23:52:47.208262+00:00 app[web.1]: failed: true,
2021-04-06T23:52:47.208262+00:00 app[web.1]: timedOut: false,
2021-04-06T23:52:47.208262+00:00 app[web.1]: isCanceled: false,
2021-04-06T23:52:47.208263+00:00 app[web.1]: killed: false
2021-04-06T23:52:47.208263+00:00 app[web.1]: }`

**Comment by Kikobeats** [comment]
429 means rate limit, it's an issue related to Heroku since it's sending too much traffic from Heroku servers to the target URL
