### ISSUE TITLE
python3 issue

### ISSUE THREAD

**Issue by teriologia** [microlinkhq/youtube-dl-exec#113]
hi I try to install package but I'm getting this error

**error C:\Users\user\Desktop\projects\bot\node_modules\youtube-dl-exec: Command failed.
Exit code: 1
Command: npx bin-version-check-cli python3 ">=3.7"
Arguments:
Directory: C:\Users\user\Desktop\projects\bot\node_modules\youtube-dl-exec
Output:
Error: Couldn't find version of `python3`
    at binaryVersion (file:///C:/Users/user/AppData/Local/npm-cache/_npx/7b761a280cf4a94b/node_modules/bin-version/index.js:55:8)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async binaryVersionCheck (file:///C:/Users/user/AppData/Local/npm-cache/_npx/7b761a280cf4a94b/node_modules/bin-version-check/index.js:14:18)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.**

but I've installed python3 already
![image](https://user-images.githubusercontent.com/35257086/179431730-d8cdded5-9cf3-49a4-902b-495e758aa0dc.png)

**Comment by Kikobeats** [comment]
Hello, just create an alias `python3` to `python` binary
