### ISSUE TITLE
process.kill('SIGKILL') throwing tinyspawn error

### ISSUE THREAD

**Issue by SnuwYx** [microlinkhq/youtube-dl-exec#203]
I am trying to use the kill method but I am being thrown a tinyspawn error each time, is this supposed to happen?

```
/<filePath>/node_modules/tinyspawn/src/index.js:22
  const error = new Error(message)
                ^

Error [ChildProcessError]: The command spawned as:

/<filePath>/node_modules/youtube-dl-exec/bin/yt-dlp https://www.youtube.com/watch?v=6xKWiCMKKJg --dump-single-json

exited with `{ code: null }` and the following trace:


    at createChildProcessError (/<filePath>/node_modules/tinyspawn/src/index.js:22:17)
    at ChildProcess.<anonymous> (/<filePath>/node_modules/tinyspawn/src/index.js:61:18)
    at ChildProcess.emit (node:events:520:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12) {
  command:  ...
```

the function i ran, i tried making as similar as the one in the doc
```
async function test() {
const youtubedl = require('youtube-dl-exec');
const url = 'https://www.youtube.com/watch?v=6xKWiCMKKJg'
const subprocess = youtubedl.exec(url, { dumpSingleJson: true })

setTimeout(() => {
  subprocess.kill('SIGKILL')
}, 5000)

result = await subprocess
console.log(result)
}
test()
```

**Comment by Kikobeats** [comment]
Can you try in this way?

```js
const youtubedl = require('youtube-dl-exec');
const url = 'https://www.youtube.com/watch?v=6xKWiCMKKJg'

youtubedl.exec(url, { dumpSingleJson: true }, { timeout: 5000, killSignal: 'SIGKILL'})
```
