### ISSUE TITLE
Sign in to confirm you�re not a bot. This helps protect our community. Learn more

### ISSUE THREAD

**Issue by sina-asghari** [microlinkhq/youtube-dl-exec#207]
hello im getting this error when im trying to download a video from youtube
i searched the internet but i didnt find anything 
![image](https://github.com/user-attachments/assets/04362246-03e4-4e98-92bf-0a5f585c29b9)

```
Failed to download video Error: ERROR: [youtube] tPEE9ZwTmy0: Sign in to confirm you�re not a bot. This helps protect our community. Learn more
    at parse (H:\code\sinilandbot\yt-download\node_modules\youtube-dl-exec\src\index.js:15:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async H:\code\sinilandbot\yt-download\node_modules\progress-estimator\src\logger.js:58:27 {
  shortMessage: 'Command failed with exit code 1: H:\\code\\sinilandbot\\yt-download\\node_modules\\youtube-dl-exec\\bin\\yt-dlp.exe https://www.youtube.com/watch?v=tPEE9ZwTmy0 --format bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4',      
  command: 'H:\\code\\sinilandbot\\yt-download\\node_modules\\youtube-dl-exec\\bin\\yt-dlp.exe https://www.youtube.com/watch?v=tPEE9ZwTmy0 --format bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4',
  escapedCommand: '"H:\\code\\sinilandbot\\yt-download\\node_modules\\youtube-dl-exec\\bin\\yt-dlp.exe" "https://www.youtube.com/watch?v=tPEE9ZwTmy0" --format "bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Comment by Kikobeats** [comment]
Hello, this library is just a wrapper over [yt-dlp/yt-dlp](https://github.com/yt-dlp/yt-dlp)

I recommend to check the documentation there 🙂
