### ISSUE TITLE
Cookies aren't being used when looking up explicit content

### ISSUE THREAD

**Issue by xythas3217** [microlinkhq/youtube-dl-exec#36]
Hello. I noticed that some videos I try to download are flagged requiring an age limit, so I'm getting a 410 error. I tried adding cookies to my request like the following:
`ytdl(
this.url,
{
	o: '-',
	q: '',
	f: 'bestaudio[ext=webm+acodec=opus+asr=48000]/bestaudio',
	r: '100K',
	cookies: 'C:\\Users\\USER\\cookies.txt'
},
{ stdio: ['ignore', 'pipe', 'ignore'] },
);`

However I am still getting the same 410 error. When I run youtube-dl manually e.g.
`youtube-dl --cookies=C:\\Users\\USER\\cookies.txt https://www.youtube.com/watch?v=j0lN0w5HVT8&t=1s`
it successfully downloads the video.

**Comment by Kikobeats** [comment]
Hello,

Thanks for reporting. The command looks legit.

Unfortunately, I need a reproducible test for helping you, since that is a feature I'm not using.

What if you try to provide cookies as a header? from CLI docs, using `--add-header FIELD:VALUE`

**Comment by xythas3217** [comment]
I resolved the issue while trying to make a reproducible test!

I was making two different requests to youtube-dl, and the first one wasnt passing in cookies, only the second.

**Comment by Laljaka** [comment]
I am having the same problem. 
Nor cookies.txt, nor passing the header works.

Here is a relevant part of my code:
```javascript
const process = ytdl.raw(
        string,
        {
                o: '-',
                // q: '',
                v: '',
                f: 'bestaudio[ext=webm+acodec=opus+asr=48000]/bestaudio',
                r: '100K',
                addHeader: 'LOGIN_INFO:AFmmF2swRAIgIbuQIwapdUbTUZ3MUJlM05aV0QzRDdxS3QxM2NZ',
        },
                { stdio: ['ignore', 'pipe', 'pipe'] },
        );
process.stderr.pipe(fs.createWriteStream('stderr.txt'));
const stream = process.stdout;
```

and here is an error from youtube-dl:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=7Do70nztRNE', '-o', '-', '-v', '-f', 'bestaudio[ext=webm+acodec=opus+asr=48000]/bestaudio', '-r', '100K', '--add-header', 'LOGIN_INFO:AFmmF2swRAIgIbuQIwapdUbTUZ3MUJlM05aV0QzRDdxS3QxM2NZ']
[debug] Adding header from command line option LOGIN_INFO:AFmmF2swRAIgIbuQIwapdUbTUZ3MUJlM05aV0QzRDdxS3QxM2NZ
[debug] Encodings: locale cp1251, fs mbcs, out cp1251, pref cp1251
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] 7Do70nztRNE: Downloading webpage
[youtube] 7Do70nztRNE: Refetching age-gated info webpage
WARNING: unable to download video info webpage: HTTP Error 410: Gone
ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\youtube.py", line 1713, in _real_extract
youtube_dl.utils.ExtractorError: Sign in to confirm your age
This video may be inappropriate for some users.
```

Header value is shortened here.
