### ISSUE TITLE
Cannot read properties of undefined (reading 'signals')

### ISSUE THREAD

**Issue by mccrush** [microlinkhq/youtube-dl-exec#69]
After connecting the library to the JS project, 
`const youtubedl = require('youtube-dl-exec')`
I get the following error in the browser console:

`_Uncaught TypeError: Cannot read properties of undefined (reading 'signals')_

    at normalizeSignal (signals.js?93eb:30:1)
    at Array.map (<anonymous>)
    at getSignals (signals.js?93eb:10:1)
    at getSignalsByName (main.js?0739:9:1)
    at eval (main.js?0739:23:1)
    at Object../node_modules/youtube-dl-exec/node_modules/human-signals/build/src/main.js (chunk-vendors.js:1210:1)
    at __webpack_require__ (app.js:849:30)
    at fn (app.js:151:20)
    at eval (error.js?c63c:2:1)
    at Object../node_modules/youtube-dl-exec/node_modules/execa/lib/error.js (chunk-vendors.js:1114:1)`

Library added to node_modules
Please, prompt in what there can be a reason. I can't find the answer on google

**Comment by Kikobeats** [comment]
Sorry for that, this is not a library oriented to be used in a browser context.
