### ISSUE TITLE
Binary Issue [Couldn't find the...]

### ISSUE THREAD

**Issue by Hiro-Beet** [microlinkhq/youtube-dl-exec#75]
Hi there,

I actually fot this problem: `Error: Couldn't find the `python` binary. Make sure it's installed and in your $PATH.`

Here is the whole log:

`npm ERR! path /home/container/node_modules/youtube-dl-exec
npm ERR! command failed
npm ERR! command sh -c npx bin-version-check-cli python ">=2"
npm ERR! Error: Couldn't find the `python` binary. Make sure it's installed and in your $PATH.
npm ERR!     at binaryVersion (file:///home/container/.npm/_npx/7b761a280cf4a94b/node_modules/bin-version/index.js:44:22)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm ERR!     at async binaryVersionCheck (file:///home/container/.npm/_npx/7b761a280cf4a94b/node_modules/bin-version-check/index.js:14:18)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/container/.npm/_logs/2022-02-17T23_06_47_501Z-debug-0.log`

I'm actually inside a container, using Docker. My home path is `/home/container`

Eviroment:

- NodeJs -> **v17.5.0**
- NPM -> **8.5.1**
- Python -> **3.9.2**

Anyone who can help me?

**Comment by Kikobeats** [comment]
I think the error is clear: `python` is not available when you perform the npm install.

Did you try `Make sure it's installed and in your $PATH`?

**Comment by Hiro-Beet** [comment]
> Make sure it's installed and in your $PATH

I'm not really sure, but Python is actually installed. So I don't really know where is the problem, it could be actually the `$PATH`,

**Comment by Hiro-Beet** [comment]
> I think the error is clear: `python` is not available when you perform the npm install.
> 
> Did you try `Make sure it's installed and in your $PATH`?



> I think the error is clear: `python` is not available when you perform the npm install.
> 
> Did you try `Make sure it's installed and in your $PATH`?

`using Python version 3.9.2 found at "/usr/bin/python3"` (from other package) so it's supposed to be in `$PATH`, help.

**Comment by jgorene** [comment]
I had the same problem on ubuntu 20.04,  I solved it by solution below.. related to #51

`sudo apt install python-is-python3`

See on [stackoverflow](https://stackoverflow.com/questions/63517713/how-to-put-python-in-path-ubuntu-20-npm-install-fails) and more on [askubuntu](https://askubuntu.com/questions/320996/how-to-make-python-program-command-execute-python-3)
