### ISSUE TITLE
Error: Command failed with exit code 1:

### ISSUE THREAD

**Issue by codingstark-dev** [microlinkhq/youtube-dl-exec#79]
Getting this error!!!
> Error: Command failed with exit code 1: /var/www/vhosts/xyz.com/httpdocs/node_modules/youtube-dl-exec/bin/youtube-dl https://www.youtube.com/watch?v=LPM1sY0ipNM --dump-single-json --no-warnings --format 140 --audio-format mp3 --no-check-certificate --prefer-free-formats --extract-audio --youtube-skip-dash-manifest --referer https://www.youtube.com/watch?v=LPM1sY0ipNM
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
    at makeError (/var/www/vhosts/xyz.com/httpdocs/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/var/www/vhosts/xyz.com/httpdocs/node_modules/execa/index.js:118:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.apiResolver (/var/www/vhosts/xyz.com/httpdocs/node_modules/next/dist/server/api-utils.js:101:9)
    at async NextNodeServer.runApi (/var/www/vhosts/xyz.com/httpdocs/node_modules/next/dist/server/next-server.js:319:9)
    at async Object.fn (/var/www/vhosts/xyz.com/httpdocs/node_modules/next/dist/server/base-server.js:486:37)
    at async Router.execute (/var/www/vhosts/xyz.com/httpdocs/node_modules/next/dist/server/router.js:228:32)
    at async NextNodeServer.run (/var/www/vhosts/xyz.com/httpdocs/node_modules/next/dist/server/base-server.js:598:29)
    at async NextNodeServer.handleRequest (/var/www/vhosts/xyz.com/httpdocs/node_modules/next/dist/server/base-server.js:305:20)

**Comment by Kikobeats** [comment]
Hello,

That's strange. Probably it's an issue related with your environment rather than the library.

I'm saying that because [Microlink API](https://microlink.io/api) can resolve the video URL without any problem:

https://api.microlink.io/?url=https://www.youtube.com/watch?v=LPM1sY0ipNM&video

Closing since unfortunately I can't do too much there – Consider ping Microlink API directly, it has daily API quota 🙂
