### ISSUE TITLE
[Command Failed] [Code 3221225781]

### ISSUE THREAD

**Issue by Orivoir** [microlinkhq/youtube-dl-exec#98]
Hi, thank for job.

After has install Python `3.10` and [youtube-dl-exec](https://www.npmjs.com/package/youtube-dl-exec), i've attempt run minimal snippet code of  [Usage documentation](https://nicedoc.io/microlinkhq/youtube-dl-exec#user-content-usage).
But i've error at output as:

```
Error: Command failed with exit code 3221225781: <PATH>\node_modules\youtube-dl-exec\bin\youtube-dl.exe https://www.youtube.com/watch?v=6xKWiCMKKJg --dump-single-json --no-warnings --no-call-home --no-check-certificate --prefer-free-formats --youtube-skip-dash-manifest --referer https://www.youtube.com/watch?v=6xKWiCMKKJg
    at makeError (<PATH>\node_modules\execa\lib\error.js:60:11)
    at handlePromise (<PATH>\node_modules\execa\index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  shortMessage: 'Command failed with exit code 3221225781: <PATH>\\node_modules\\youtube-dl-exec\\bin\\youtube-dl.exe https://www.youtube.com/watch?v=6xKWiCMKKJg --dump-single-json --no-warnings --no-call-home --no-check-certificate --prefer-free-formats --youtube-skip-dash-manifest --referer https://www.youtube.com/watch?v=6xKWiCMKKJg',
  command: '<PATH>\\node_modules\\youtube-dl-exec\\bin\\youtube-dl.exe https://www.youtube.com/watch?v=6xKWiCMKKJg --dump-single-json --no-warnings --no-call-home --no-check-certificate --prefer-free-formats --youtube-skip-dash-manifest --referer https://www.youtube.com/watch?v=6xKWiCMKKJg',
  escapedCommand: '"<PATH>\\node_modules\\youtube-dl-exec\\bin\\youtube-dl.exe" "https://www.youtube.com/watch?v=6xKWiCMKKJg" --dump-single-json --no-warnings --no-call-home --no-check-certificate --prefer-free-formats --youtube-skip-dash-manifest --referer "https://www.youtube.com/watch?v=6xKWiCMKKJg"',
  exitCode: 3221225781,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
``` 

Output error is not very *dev friendly* give only a not documented error code `3221225781` and call stack.

I've see at other issue same problem has been opened #30 but never response has been provide.
I porpose documented for error code provide at output.

**Comment by Orivoir** [comment]
Thank for feedback at `\node_modules\youtube-dl-exec\bin` i've a `youtube-dl.exe` file.
But i can't use this exec file from any command i receveid native error message
with below log:

```bash
youtube-dl.exe - System Error:

MSVCR100.dll is missing
```

[CLI screenshot](https://ibb.co/82LFr2D)

Error message is in french lang, but indicate **MSVCR100.dll is missing**

**Comment by Kikobeats** [comment]
So it's an error in machine; It looks like a DLL on Windows is necessary and you it's missing
